name: Vue3-TS deployer # Actions 名字

on: # 触发条件
  push:
    branches:
      - gh-pages # 仅向gh-pages 分支 push 时触发

jobs:
  build: # job id
    name: Build and publish # job 名，不写默认使用 job id
    runs-on: ubuntu-latest # 运行环境，可选 ubuntu-latest, ubuntu-18.04, ubuntu-16.04, windows-latest, windows-2019, windows-2016, macOS-latest, macOS-10.14

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Packages
        run: |
          npm install

      - name: Build page
        run: |
          npm run build

      - name: Deploy to gh-pages
        env:
          GH_REF: github.com/yingliyu/vue3-ts-pro.git
          # github.com/lemon1499/lemon1499.github.io.git
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_VUE3_PRO }} # github token
          # CODING_REF: e.coding.net/ylyu/blog.git
          # git.dev.tencent.com/ylyu/ylyu.git
          #  CODING_TOKEN: ${{ secrets.CODING_ACCESS_TOKEN }} # coding token
        run: |
          git config --global user.name "yingliyu"
          git config --global user.email "404997046@qq.com"
          git clone https://${GH_REF} .deploy_git
          cd .deploy_git
          git checkout master
          cd ../
          mv .deploy_git/.git/ ./dist/
          cd ./dist/
          git add .
          git commit -m ":construction_worker:CI built at `date +"%Y-%m-%d %H:%M:%S"`"
          # GitHub Pages
          git push --force --quiet "https://${ACCESS_TOKEN}@${GH_REF}" master:master
          # Coding Pages 
          # git push --force --quiet "https://pteijvzl89as:0b3c6929c53bc1aaaf49f67a3d714eff40dd4a23@${CODING_REF}" master:master
